{% set name = "tobler" %}
{% set version = "0.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8d612d6930e963d8bdd18b8b39d104f0b6b514062e491dca72f0d1e274dde1c0

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5
    - pip
    - setuptools >=61.0
    - setuptools-scm >=6.2
  run:
    - python >=3.5
    - pandas
    - numpy >=1.16
    - geopandas >=0.13
    - rasterio
    - rasterstats
    - statsmodels
    - scipy
    - libpysal >=4.2.0
    - tqdm
    - joblib

test:
  imports:
    - tobler

about:
  home: https://github.com/pysal/tobler
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Tobler is a python package for areal interpolation, dasymetric mapping, and change of support.
  description: |
    Tobler is a python package for areal interpolation, dasymetric mapping, and change of support.
  doc_url: https://pysal.org/tobler/
  dev_url: https://github.com/pysal/tobler/

extra:
  recipe-maintainers:
    - knaaptime
    - sjsrey
    - martinfleis
    - jGaboardi
